# Minimal GoReleaser config for a3s
project_name: a3s

before:
  hooks:
    - go mod tidy

builds:
  - id: a3s
    main: ./cmd/a3s
    binary: a3s
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    # Pi 3 optimization: build sequentially to avoid memory issues
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: a3s
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: johnoct
    name: a3s
  draft: false
  prerelease: auto
  name_template: '{{.ProjectName}} v{{.Version}}'
  
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'